" Vundle Settings {{{
set nocompatible
filetype off
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'airblade/vim-gitgutter'
" Plugin 'mhinz/vim-startify'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" }}}

" Basic Settings {{{
" highlighting
syntax on
filetype on
set background=dark
set cursorline
" set number and let relative line number show when done typing
set number
autocmd InsertEnter * :set number
autocmd InsertLeave * :set relativenumber
set numberwidth=2           " no need to have three digit line number
" tabbing
set tabstop=2
set expandtab
set shiftwidth=2
set softtabstop=2
" folding settings
set foldmethod=indent
set foldnestmax=10
set nofoldenable
set foldlevel=1
" using solarized color scheme
colorscheme solarized
if !has('gui_running')
  " Compatibility for Terminal
  let g:solarized_termtrans=1
  let g:solarized_termcolors=16
endif
" force to use 256 color to avoid strange color in linux terminal
set t_Co=256      
" searching
: set incsearch
: set hlsearch
" disable swap files creation
set noswapfile
" }}}

" Mappings {{{
" test surrounding characters
inoremap ( ()<Esc>i
" }}}
